services:
  nginx:
    build: .
    container_name: nginx-dev-2
    ports:
      - "80:80"
      - "443:443"
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
      - "8005:8005"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./logs:/var/log/nginx
      - ./servico1:/usr/share/nginx/servico1
      - ./servico2:/usr/share/nginx/servico2
      - ./performance:/usr/share/nginx/performance
      - ./local:/usr/share/localssl
    restart: unless-stopped
    