proxy_cache_path /var/cache/nginx/servico2_cache keys_zone=s2_cache:10m inactive=60m;
server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /servico1 {
        proxy_pass http://localhost:8001/;
    }

    location /servico2 {
        proxy_pass http://localhost:8002/;
        proxy_cache s2_cache;
        proxy_cache_valid  1m;
        add_header X-Cache-Status $upstream_cache_status;
    }

    error_page 404 400 401 /error.html;

    # proxy example
    # location /api {
    #     proxy_pass http://backend:3000
    # }

    # location ~* \.(jpg|jpeg|png|gif|ico|css|js)$ {
    #     expires 1y;
    #     add_header Cache-Control "public, imutable";
    # }
}