upstream services {
    # least_conn; send request to server with less active connections
    # server localhost:8001 weight=2; 
    server localhost:8001 fail_timeout=120s; 
    # setting a backup server
    # server localhost:8002 backup; 
    server localhost:8002; 
}
server{
    listen 8003;
    server_name localhost;   

    location / {
        proxy_pass http://services;
        proxy_set_header X-Real-IP $remote_addr;
    }
}