log_format services 'Remote Addr: $remote_addr, Time: [$time_local], Request: "$request" '
                    'Status: $status" ';

server {
    listen 8001;
    server_name localhost;
    access_log /var/log/nginx/servico1.log services;

    location / {
        root /usr/share/nginx/servico1;
        index index.html;
    }
}

server {
    listen 8002;
    server_name localhost;
    access_log /var/log/nginx/servico2.log services;

    location / {
        root /usr/share/nginx/servico2;
        index index.html;
    }
}